# Generated by Django 5.1.6 on 2025-02-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Learning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название модуля", max_length=50, verbose_name="Название модуля"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Укажите описание модуля", null=True, verbose_name="Описание модуля"
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательный модуль",
                "verbose_name_plural": "Образовательные модули",
            },
        ),
    ]
